version: "3.8"

services:
  serverw:
    image: idcmardelplata/serverw
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - flagd

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    ports:
      - "8013:8013"
    volumes:
      - ./:/etc/flagd/
    command: ["start", "--uri", "file:/etc/flagd/flags.flagd.json"]
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
